export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LANG="en_US.UTF-8"
# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh
export NVIM_TUI_ENABLE_TRUE_COLOR=1
export EDITOR=nvim

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="sammy"

# Set to this to use case-sensitive completion
export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh
unsetopt correct_all

# Customize to your needs...
export PATH=/usr/local/bin:/usr/local/sbin:/usr/texbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin
export PATH=$HOME/.local/haskell/.cabal-sandbox/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.rbenv/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH=node_modules/.bin:$PATH
export PATH=.cabal-sandbox/bin:$PATH

eval "$(rbenv init -)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export GOPATH="$HOME/go"
export GO15VENDOREXPERIMENT=1
export PATH=$PATH:/usr/local/opt/go/libexec/bin:$GOPATH/bin

export COPYFILE_DISABLE=true

export NODE_PATH=/usr/local/lib/node

export MACOSX_DEPLOYMENT_TARGET="10.11"

alias e='open -a Emacs'
alias serve='python -mSimpleHTTPServer'
alias feature='git flow feature'
alias vim=nvim
alias vi=nvim

export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CFLAGS="-I/usr/local/opt/openssl/include"
export CPPFLAGS="-I/usr/local/opt/openssl/include"
export SWIG_FEATURES="-cpperraswarn -includeall -I/url/local/opt/openssl/include"
