export LANG="en_US.UTF-8"
# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="yumike"

# Set to this to use case-sensitive completion
export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh
unsetopt correct_all

# Customize to your needs...
export PATH=node_modules/.bin:$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/opt/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin
export PATH=$HOME/.rbenv/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH="/usr/local/share/npm/bin:$PATH"

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Projects
export VIRTUALENVWRAPPER_LOG_DIR=$WORKON_HOME
source "/usr/local/bin/virtualenvwrapper.sh"

export COPYFILE_DISABLE=true
export VIRTUALENV_USE_DISTRIBUTE=true

export NODE_PATH=/usr/local/lib/node

export MACOSX_DEPLOYMENT_TARGET=10.8

alias serve='python -mSimpleHTTPServer'
alias feature='git flow feature'

eval "$(rbenv init -)"

if [[ "$TERM" != "screen-256color" ]]; then
  tmux attach-session -t "$USER" || tmux new-session -s "$USER"
fi
